### ISSUE TITLE
cannot import name 'keras_export' from 'keras'

### ISSUE THREAD

**Issue by Ldoz13** [NREL/polyID#4]
I am getting this `cannot import name 'keras_export' from 'keras'` error. in the first code block itself.
I have installed the following dependencies using pip.

- m2p
- rdkit
- polyid

Tried using Colab, SageMaker Lab Studio and my Laptop. All are throwing this error.

**Comment by jlaw9** [comment]
Apologies for the delay @Ldoz13, I didn't have notifications setup. 

Can you please provide more details about your python environment? What version of python and tensorflow are you using?

**Comment by jlaw9** [comment]
I believe this should be fixed with the updated environment.yml file.
